export const projectsData = [
  {
    name: "Task Management Tool",
    image: require("../../assets/management-tool.png"),
    info: [
      "1st Mern stack web application",
      "Created REST APIs using node & express",
      "Implemented file uploads using multer & context api",
      "Its a task management tool, the roles customer,expert,admin",
      "Customer-creates task, Admin-assign tasks",
      "Deployed frontend on netlify & backend on render",
    ],
    techUsed: "MERN Stack, Netflify & Render",
    link: "https://duwork-task-managment-tool.netlify.app",
  },
  {
    name: "Blog Website",
    image: require("../../assets/blog-website.png"),
    info: [
      "Built a nextjs app, used dynamic routing, serverside props, etc..",
      "Added firebase google authentication",
      "Used firebase database & storage",
      "Video & Images can be uploaded",
      "User can upload blogs on various categories like health, cooking, sports, etc..",
      "Deployed on vercel",
    ],
    techUsed: "Nextjs, Vercel",
    link: "https://blog-website-tau.vercel.app/",
  },
  {
    name: "Swigato Web App",
    image: require("../../assets/swigato.png"),
    info: [
      "1st full stack application using php, its a food ordering website",
      "Learnt lot of php concepts & wrote mysql queries",
      "Created more than 15 pages & worked with xampp, phpmyadmin",
      "Created Admin panel which handles orders,accounts,food,etc",
      "Gained lot of learning in css",
      "Deployed on 000Webhostapp.com",
    ],
    techUsed: "Php, 000webhostapp",
    link: "https://swigato.000webhostapp.com/",
  },
  {
    name: "Me Chat",
    image: require("../../assets/me-chat.png"),
    info: [
      "Created a nextjs chat application which renders chat on realtime basis",
      "Used firebase database & google authentication",
      "Added encryption & decryption of messages using cryptjs",
      "User can do personal chat & global group chat",
      "Deployed on vercel",
    ],
    techUsed: "Nextjs, Vercel",
    link: "https://me-chat-beryl.vercel.app/",
  },
  {
    name: "Netflix Clone",
    image: require("../../assets/netflix.png"),
    info: [
      "Built using reactjs & firebase, Taken help from Sonny Sangha",
      "Implemented firebase email/password authentication",
      "Used TMDB api for fetching movies data",
      "Clicking on movie shows trailer, found from youtube",
      "Worked with react redux, used to avoid props drilling",
      "Implemented payment gateway using stripe (firebase <---firebase stripe extension--->stripe)",
      "Deployed on firebase",
    ],
    techUsed: "Reactjs, Firebase",
    link: "https://netflix-build-70a76.web.app/",
  },
  {
    name: "Voting Programming Language",
    image: require("../../assets/voting.png"),
    info: [
      "Built using Django",
      "Worked on Model, View, Templates",
      "Used postgresql for database",
      "Created 3 view signup,signin & homepage",
      "Gained lot of learning in css",
      "Deployed on railway.app",
    ],
    techUsed: "Django, Railway",
    link: "https://programming-voting-app-production.up.railway.app/",
  },
];
